name: Nosli ICT Direct
favicon: null
layout_spectrum: 0.6118177997414023
typography_spectrum: 0.11201974051073194
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.794637702871114
  lightness: 0.24502320471219718
  saturation: 0.755701873684302
  rhythmicContrast: 0.18565713660791516
purpose: []
