layout_spectrum: 0.5088989203795791
typography_spectrum: 0.5365872320253402
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.5929857345763594
  lightness: 0.42921262490563095
  saturation: 0.6250603345688432
  rhythmicContrast: 0.6934221216943115
name: Nosli ICT Direct
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
